apiVersion: v1
kind: Service
metadata:
  name: metrics-agent
  namespace: monitoring
  labels:
    app: metrics-agent
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: metrics-agent
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  clusterIP: None